#pragma once
#include <list>
#include <tuple>
#include <iostream>
#include <sstream>
#include <cfloat>
#include <cmath>
#include <ctime>
#include <algorithm>
#include <map>
#include <opencv2/opencv.hpp>
#include <opencv2/nonfree/nonfree.hpp>
#include <opencv2/nonfree/features2d.hpp>
